name: Setup Test Environment
description: "Install poetry, use poetry to install dependencies"

runs:
  using: "composite"
  steps:
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
    - name: Install Poetry
      run: python3 -m pip install poetry==1.1.15 --upgrade pip
    - name: Configure Poetry
      run: poetry config ~/poetry-cache/
    - name: Setup Caching
      uses: actions/cache@v3
      with:
        path: ~/pypoetry-cache/
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: python --version
    - name: Install dependencies
      run: poetry install --no-interaction
