name: Checks
on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup_test_environment
      - run: poetry run python -m unittest discover --verbose tests/integration
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup_test_environment
      - run: poetry run python -m unittest discover --verbose tests
  lint-commit-messages:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
