name: Test and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  # the jobs below are taken from the actions in https://github.com/relekang/python-semantic-release under MIT License
  beautify:
    needs: [ checks ]
    uses: ./.github/workflows/beautify.yml

  coverage:
    needs: [ checks ]
    uses: ./.github/workflows/coverage.yml

  semantic-release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    concurrency: release
    needs: [checks, beautify]

    outputs:
      new_version: ${{ steps.version.outputs.VERSION }}
      new_sha: ${{ steps.sha.outputs.SHA }}

    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.beautify.outputs.new_sha }}

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_PROJECT_API_TOKEN }}
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email action@github.com
          semantic-release publish
