name: Test and Publish
on:
  push:
    branches:
      - ci-cd

jobs:
  unit-tests:
    uses: ./.github/workflows/unit_tests.yml
  integration-tests:
    uses: ./.github/workflows/integration_tests.yml

  # the jobs below are taken from the actions in https://github.com/relekang/python-semantic-release under MIT License
  beautify:
    name: Beautify
    runs-on: ubuntu-latest
    concurrency: push
    needs: [ unit-tests, integration-tests ]
    outputs:
      new_sha: ${{ steps.sha.outputs.SHA }}

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Black
        run: python -m pip install black

      - name: Beautify with Black
        run: python -m black .

      - name: Install isort
        run: python -m pip install isort

      - name: Sort imports
        run: python -m isort --profile black .

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: beautify ${{ github.sha }}'
          name: github-actions
          email: action@github.com

      - name: Get new SHA
        id: sha
        run: |
          new_sha=$(git rev-parse HEAD)
          echo "::set-output name=SHA::$new_sha"

  semantic-release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    concurrency: push
    needs: [unit-tests, integration-tests, beautify]
    outputs:
      new_version: ${{ steps.version.outputs.VERSION }}
      new_sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ needs.beautify.outputs.new_sha }}
      - name: install relekang/python-semantic-release
        run: python3 -m pip install python-semantic-release
      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.TESTPYPI_ACCOUNT_API_TOKEN }}

