name: Test and Publish
on:
  push:
    branches:
      - 'main'

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  # the jobs below are taken from the actions in https://github.com/relekang/python-semantic-release under MIT License
  beautify:
    name: Beautify
    runs-on: ubuntu-latest
    concurrency: push
    needs: [ checks ]
    outputs:
      new_sha: ${{ steps.sha.outputs.SHA }}

    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Black
        run: python -m pip install black

      - name: Beautify with Black
        run: python -m black .

      - name: Install isort
        run: python -m pip install isort

      - name: Sort imports
        run: python -m isort --profile black .

      - name: Commit and push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'style: beautify ${{ github.sha }}'
          name: github-actions
          email: action@github.com

      - name: Get new SHA
        id: sha
        run: |
          new_sha=$(git rev-parse HEAD)
          echo "SHA=$new_sha" >> $GITHUB_OUTPUT

  semantic-release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    concurrency: release
    needs: [checks, beautify]
    outputs:
      new_version: ${{ steps.version.outputs.VERSION }}
      new_sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.beautify.outputs.new_sha }}
      - name: Fetch main
        run: git fetch --prune --force origin refs/heads/main:refs/remotes/origin/main
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
      - name: Install dependencies
        run: |
          python3 -m pip install poetry==1.1.15 --upgrade pip
          poetry config virtualenvs.create false
      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_PROJECT_API_TOKEN }}
