name: pre-commit

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - pre-commit-hooks-test

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
